databases:
  - name: tiles-db
    plan: free

services:
  - type: web
    name: tiles-stock-app
    env: python
    rootDirectory: tiles_stock_app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tiles-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
